[options]
default_indent = 2
shiftwidth=2
# guifont = 'DejaVu Sans Mono for Powerline 14'
guifont = "Sauce Code Pro Nerd Font Complete Mono:h22"
max_column = 110
colorcolumn = 120
automatic_update = true
filetree_direction = "right"
# filemanager = "nerdtree"
rehash256 = 1
autowrite = 1
spacevim_max_column = 110 
bootstrap_before = "custom_init#before"
updatetime=100
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
# colorscheme = "gruvbox"
# colorscheme_bg = "dark"
colorscheme = "gruvbox"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
   # options for statusline
# Set the statusline separators of statusline, default is "arrow"
statusline_separator = "arrow"
# Set the statusline separators of inactive statusline
statusline_inactive_separator = "bar"

# Set SpaceVim buffer index type
buffer_index_type = 4
# 0: 1 ➛ ➊
# 1: 1 ➛ ➀
# 2: 1 ➛ ⓵
# 3: 1 ➛ ¹
# 4: 1 ➛ 1

# Enable/Disable show mode on statusline
enable_statusline_mode = true

# left sections of statusline
statusline_left_sections = [
   'winnr',
   'major mode',
   'filename',
   'fileformat',
   'minor mode lighters',
   'version control info',
   'search status'
]
# right sections of statusline
statusline_right_sections = [
   'cursorpos',
   'percentage',
   'input method',
   'date',
   'time'
]

# 'winnr' window number
# 'syntax checking'
# 'filename' file name
# 'fileformat' file format
# 'major mode'
# 'minor mode lighters'
# 'cursorpos' cursor position
# 'percentage' content range
# 'date' date
# 'time' time
# 'whitespace' line number with trailing space at the end
# 'battery status' battery status
# 'input method' input method
# 'search status' search indexi

 
bootstrap_before = "myspacevim#before"
   
#      Syntax checking on the fly feature, disabled by default.
lint_on_the_fly = true
# spacevim_lint_on_save = true
enable_neomake = true
# enable_ale = true
# neomake_open_list = true
go_rename_command = 'gopls'
go_metalinter_command='golangci-lint'
go_metalinter_autosave = true
go_metalinter_enabeld = ['deadcode', 'errcheck', 'gosimple', 'govet', 'staticcheck', 'typecheck', 'unused', 'varcheck']
# go_list_type = "quickfix"
# go_fmt_fail_silently = 1
# go_addtags_transform = "camelcase"
# go_highlight_types = 1
# go_highlight_fields = 1
# go_highlight_functions = 1
# go_highlight_function_calls = 1
# go_highlight_operators = 1
# go_highlight_extra_types = 1
# go_highlight_build_constraints = 1
# go_highlight_generate_tags = 1
# go_metalinter_deadline = "5s"
# go_def_mode = 'godef'
# go_decls_includes = "func,type"
# go_auto_type_info = 1
# go_auto_sameids = 1
#Enable autocomplete layer

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "checkers"

[[layers]]
  name = "debug"

[[layers]]
	  name = "lang#WebAssembly"
	
[[layers]]
	  name = "lang#assembly"

[[layers]]
	  name = "lang#c"
	
[[layers]]
	  name = "lang#rust"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "format"

[[layers]]
  name = "lang#go"
  

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[custom_plugins]]
  name = "sebdah/vim-delve"
  merged = false

[[custome_plugin]]
  name = "SirVer/ultisnips"

[[custome_plugin]]
 name = "luochen1990/rainbow"
 merged = 0

[[layers]]
  name = "tmux"

[[layers]]
name = "lsp"
filetypes = [
#"rust",
#"clangd",
"go",
# "javascript",
#"typescript",
"sh"
]

[layers.override_cmd]
    go = ['rename','gopls','go-langserver', '-mode', 'stdio'] 

[[layers]]
  name = "test"

[layers.override_config]
    go_runner = "delve"
    rust_runner = "cargotest"

[[layers]]
  name = "colorscheme"

[[custom_plugins]]
  name = "haya14busa/vim-gtrans"
  merged = 0

[[custom_plugins]]
  name = "AndrewRadev/splitjoin.vim"
  merged = 0

[[custom_plugins]]
  name = "SirVer/ultisnips"
  merged = 0

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "default"

[[layers]]
  name = "sudo" 
